import glob
Import('env')

# Loop over libraries, building each
this_env=env.Clone()
this_env.Prepend(LIBS=["libstreamingReco","libstreamingRecoExt","JANA","dl","pthread","ccdb"]) 


progs=['streamingReco']
for prog in progs:
    src =Glob(prog+'/*.cc')
    this_env.Program(source=src,target='#/bin/'+prog)	

