import glob
from utils import *
Import('env mc_enable')

# Loop over libraries, building each
libs=['system','HallD','FT','DAQ','TT','Trigger','FT/hdbscandir','FT/kmeans']

src = []
for lib in libs:
	reldir = str(lib)
	absdir = Dir('#/src/libraries/'+reldir).srcnode().abspath
	AddROOTdict(env,reldir,absdir)
	src = src+Glob(lib+'/*.cc')

env.SharedLibrary(source=src,target='#/lib/streamingReco')
