from utils import *
Import('env debug')

plugins = getSubdirs('./')


for plugin in plugins:
    env_plugins=env.Clone()

    # Disable rootspy and janaview plugins for now  9/18/2020 DL
    if ("rootspy" in plugin): continue
    if ("janaview" in plugin): continue

    print  bcolors.OKBLUE,"Found plugin ",plugin,bcolors.ENDC
    
    #save the relative dir and the absolute dir
    reldir = str(plugin)
    absdir = Dir('#/src/plugins/'+reldir).srcnode().abspath   
    #We do not want to increment "at libitum" CPPPATH
    tmp_cpppath=env_plugins['CPPPATH'];    
    env_plugins.Append(CPPPATH=absdir)
    
    if ("rootspy" in plugin):
        print bcolors.OKBLUE,"Adding rootspy libs + cmsg libs ",bcolors.ENDC
        env_plugins.Append(LIBS=["RootSpy-client","RootSpy","cmsgRegex","cmsgxx","cmsg"])
       

  
    
    #Add root dictionaries if necessary
    AddROOTdict(env_plugins,reldir,absdir)
        
    #Compile macros
    AddROOTSpyMacros(env_plugins,reldir,absdir)
        
        
    plugin_src  = Glob(reldir+'/*.cc')
    if (platform.system()!="Darwin"):
    	env_plugins.AppendUnique(LINKFLAGS='-Wl,-z,defs') #Very important to make sure we won't get errors at run time
    
    env_plugins.Append(LIBS=["libstreamingRecoExt","libstreamingReco","JANA","dl","pthread","ccdb"]) 
    env_plugins.SharedLibrary(source=plugin_src,target='#/lib/plugins/'+plugin,SHLIBPREFIX='',SHLIBSUFFIX='.so')
    env_plugins.Replace(CPPPATH = tmp_cpppath)        
    
